/**
 * @harpa/api-contract — single source of HTTP shape.
 *
 * Re-exports Zod schemas + generated OpenAPI types so the mobile client
 * and the API server type-check against the same definitions.
 */
export * from './schemas/index.js';
export * as schemas from './schemas/index.js';

// Generated OpenAPI types (regenerated by `pnpm --filter @harpa/api-contract gen:types`).
// Consumers (mobile client) build a typed fetch wrapper on top of `paths`.
export type { paths, operations } from './generated/types.js';
