/**
 * @harpa/api-contract — single source of HTTP shape.
 *
 * Re-exports Zod schemas + generated OpenAPI types so the mobile client
 * and the API server type-check against the same definitions.
 */
export * from './schemas/index.js';
export * as schemas from './schemas/index.js';

// Generated OpenAPI types (regenerated by `pnpm --filter @harpa/api-contract gen:types`).
// Consumers (mobile client) build a typed fetch wrapper on top of `paths`.
// Keep the generated operation map under a distinct type name so the runtime
// `operations` schema namespace remains usable from this package barrel.
export type { paths, operations as OpenApiOperations } from './generated/types.js';
