/**
 * @harpa/api-contract — single source of HTTP shape.
 *
 * Re-exports Zod schemas + generated OpenAPI types so the mobile client
 * and the API server type-check against the same definitions.
 */
export * from './schemas/index.js';
export * as schemas from './schemas/index.js';

// Generated OpenAPI types (regenerated by `pnpm --filter @harpa/api-contract gen:types`).
// Consumers (mobile client) build a typed fetch wrapper on top of `paths`.
export type { paths, operations } from './generated/types.js';

/**
 * Branded TS types for prefixed public slugs. A `ProjectSlug` cannot
 * be passed where a `ReportSlug` is expected, even though both are
 * strings at runtime. See docs/v4/arch-ids-and-urls.md.
 */
export type ProjectSlug = string & { readonly __brand: 'ProjectSlug' };
export type ReportSlug = string & { readonly __brand: 'ReportSlug' };

export function projectSlugBrand(s: string): ProjectSlug {
  return s as ProjectSlug;
}
export function reportSlugBrand(s: string): ReportSlug {
  return s as ReportSlug;
}
