/**
 * AUTO-GENERATED by apps/mobile/scripts/gen-hooks.ts. DO NOT EDIT.
 *
 * Run `pnpm gen:api` to regenerate. The spec-drift gate
 * (scripts/check-spec-drift.sh) fails CI if this file is out of date.
 *
 * Each hook is a thin wrapper over `request(path, method, ...)` from
 * `./client.js`. Mutations call into the central invalidation map
 * (`./invalidation.js`) so post-write cache busts are declarative
 * and tested.
 */
/* eslint-disable */
import {
  useQuery,
  useMutation,
  useQueryClient,
  type UseQueryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query';
import { request, type RequestBody, type ResponseBody, type PathParams, type QueryParams } from './client';
import { ApiError } from './errors';
import { INVALIDATIONS, INVALIDATIONS_NONE } from './invalidation';

// ─── healthz ───────────────────────────────────────────
export function useHealthQuery(
  input?: { query?: QueryParams<"/healthz", "get"> } | void,
  options?: Omit<UseQueryOptions<ResponseBody<"/healthz", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/healthz", "get">, ApiError>({
    queryKey: ["health", (input as any)?.query] as const,
    queryFn: ({ signal }) => request("/healthz", "get", { query: (input as any)?.query, signal }),
    ...options,
  });
}

// ─── auth ───────────────────────────────────────────
export function useStartOtpMutation(
  options?: UseMutationOptions<ResponseBody<"/auth/otp/start", "post">, ApiError, { body: RequestBody<"/auth/otp/start", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/auth/otp/start", "post">, ApiError, { body: RequestBody<"/auth/otp/start", "post"> }>({
    mutationFn: (vars) => request("/auth/otp/start", "post", { body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useStartOtpMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useVerifyOtpMutation(
  options?: UseMutationOptions<ResponseBody<"/auth/otp/verify", "post">, ApiError, { body: RequestBody<"/auth/otp/verify", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/auth/otp/verify", "post">, ApiError, { body: RequestBody<"/auth/otp/verify", "post"> }>({
    mutationFn: (vars) => request("/auth/otp/verify", "post", { body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useVerifyOtpMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useLogoutMutation(
  options?: UseMutationOptions<ResponseBody<"/auth/logout", "post">, ApiError, void>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/auth/logout", "post">, ApiError, void>({
    mutationFn: (vars) => request("/auth/logout", "post"),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useLogoutMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

// ─── me ───────────────────────────────────────────
export function useMeQuery(
  input?: { query?: QueryParams<"/me", "get"> } | void,
  options?: Omit<UseQueryOptions<ResponseBody<"/me", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/me", "get">, ApiError>({
    queryKey: ["me", (input as any)?.query] as const,
    queryFn: ({ signal }) => request("/me", "get", { query: (input as any)?.query, signal }),
    ...options,
  });
}

export function useUpdateMeMutation(
  options?: UseMutationOptions<ResponseBody<"/me", "patch">, ApiError, { body: RequestBody<"/me", "patch"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/me", "patch">, ApiError, { body: RequestBody<"/me", "patch"> }>({
    mutationFn: (vars) => request("/me", "patch", { body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useUpdateMeMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useMeUsageQuery(
  input?: { query?: QueryParams<"/me/usage", "get"> } | void,
  options?: Omit<UseQueryOptions<ResponseBody<"/me/usage", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/me/usage", "get">, ApiError>({
    queryKey: ["meUsage", (input as any)?.query] as const,
    queryFn: ({ signal }) => request("/me/usage", "get", { query: (input as any)?.query, signal }),
    ...options,
  });
}

// ─── projects ───────────────────────────────────────────
export function useListProjectsQuery(
  input?: { query?: QueryParams<"/projects", "get"> } | void,
  options?: Omit<UseQueryOptions<ResponseBody<"/projects", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/projects", "get">, ApiError>({
    queryKey: ["projects", (input as any)?.query] as const,
    queryFn: ({ signal }) => request("/projects", "get", { query: (input as any)?.query, signal }),
    ...options,
  });
}

export function useCreateProjectMutation(
  options?: UseMutationOptions<ResponseBody<"/projects", "post">, ApiError, { body: RequestBody<"/projects", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects", "post">, ApiError, { body: RequestBody<"/projects", "post"> }>({
    mutationFn: (vars) => request("/projects", "post", { body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useCreateProjectMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useProjectQuery(
  input: { params: PathParams<"/projects/{project}", "get">; query?: QueryParams<"/projects/{project}", "get"> },
  options?: Omit<UseQueryOptions<ResponseBody<"/projects/{project}", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/projects/{project}", "get">, ApiError>({
    queryKey: ["project", (input as any).params, (input as any).query] as const,
    queryFn: ({ signal }) => request("/projects/{project}", "get", { params: (input as any).params, query: (input as any).query, signal }),
    ...options,
  });
}

export function useUpdateProjectMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}", "patch">, ApiError, { params: PathParams<"/projects/{project}", "patch">; body: RequestBody<"/projects/{project}", "patch"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}", "patch">, ApiError, { params: PathParams<"/projects/{project}", "patch">; body: RequestBody<"/projects/{project}", "patch"> }>({
    mutationFn: (vars) => request("/projects/{project}", "patch", { params: (vars as any).params, body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useUpdateProjectMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useDeleteProjectMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}", "delete">, ApiError, { params: PathParams<"/projects/{project}", "delete"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}", "delete">, ApiError, { params: PathParams<"/projects/{project}", "delete"> }>({
    mutationFn: (vars) => request("/projects/{project}", "delete", { params: (vars as any).params }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useDeleteProjectMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useProjectMembersQuery(
  input: { params: PathParams<"/projects/{project}/members", "get">; query?: QueryParams<"/projects/{project}/members", "get"> },
  options?: Omit<UseQueryOptions<ResponseBody<"/projects/{project}/members", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/projects/{project}/members", "get">, ApiError>({
    queryKey: ["projectMembers", (input as any).params, (input as any).query] as const,
    queryFn: ({ signal }) => request("/projects/{project}/members", "get", { params: (input as any).params, query: (input as any).query, signal }),
    ...options,
  });
}

export function useAddProjectMemberMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}/members", "post">, ApiError, { params: PathParams<"/projects/{project}/members", "post">; body: RequestBody<"/projects/{project}/members", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}/members", "post">, ApiError, { params: PathParams<"/projects/{project}/members", "post">; body: RequestBody<"/projects/{project}/members", "post"> }>({
    mutationFn: (vars) => request("/projects/{project}/members", "post", { params: (vars as any).params, body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useAddProjectMemberMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useRemoveProjectMemberMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}/members/{user}", "delete">, ApiError, { params: PathParams<"/projects/{project}/members/{user}", "delete"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}/members/{user}", "delete">, ApiError, { params: PathParams<"/projects/{project}/members/{user}", "delete"> }>({
    mutationFn: (vars) => request("/projects/{project}/members/{user}", "delete", { params: (vars as any).params }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useRemoveProjectMemberMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useUpdateProjectMemberMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}/members/{user}", "patch">, ApiError, { params: PathParams<"/projects/{project}/members/{user}", "patch">; body: RequestBody<"/projects/{project}/members/{user}", "patch"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}/members/{user}", "patch">, ApiError, { params: PathParams<"/projects/{project}/members/{user}", "patch">; body: RequestBody<"/projects/{project}/members/{user}", "patch"> }>({
    mutationFn: (vars) => request("/projects/{project}/members/{user}", "patch", { params: (vars as any).params, body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useUpdateProjectMemberMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useProjectReportsQuery(
  input: { params: PathParams<"/projects/{project}/reports", "get">; query?: QueryParams<"/projects/{project}/reports", "get"> },
  options?: Omit<UseQueryOptions<ResponseBody<"/projects/{project}/reports", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/projects/{project}/reports", "get">, ApiError>({
    queryKey: ["projectReports", (input as any).params, (input as any).query] as const,
    queryFn: ({ signal }) => request("/projects/{project}/reports", "get", { params: (input as any).params, query: (input as any).query, signal }),
    ...options,
  });
}

export function useCreateReportMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}/reports", "post">, ApiError, { params: PathParams<"/projects/{project}/reports", "post">; body: RequestBody<"/projects/{project}/reports", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}/reports", "post">, ApiError, { params: PathParams<"/projects/{project}/reports", "post">; body: RequestBody<"/projects/{project}/reports", "post"> }>({
    mutationFn: (vars) => request("/projects/{project}/reports", "post", { params: (vars as any).params, body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useCreateReportMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useReportQuery(
  input: { params: PathParams<"/projects/{project}/reports/{number}", "get">; query?: QueryParams<"/projects/{project}/reports/{number}", "get"> },
  options?: Omit<UseQueryOptions<ResponseBody<"/projects/{project}/reports/{number}", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/projects/{project}/reports/{number}", "get">, ApiError>({
    queryKey: ["report", (input as any).params, (input as any).query] as const,
    queryFn: ({ signal }) => request("/projects/{project}/reports/{number}", "get", { params: (input as any).params, query: (input as any).query, signal }),
    ...options,
  });
}

export function useUpdateReportMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}/reports/{number}", "patch">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}", "patch">; body: RequestBody<"/projects/{project}/reports/{number}", "patch"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}/reports/{number}", "patch">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}", "patch">; body: RequestBody<"/projects/{project}/reports/{number}", "patch"> }>({
    mutationFn: (vars) => request("/projects/{project}/reports/{number}", "patch", { params: (vars as any).params, body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useUpdateReportMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useDeleteReportMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}/reports/{number}", "delete">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}", "delete"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}/reports/{number}", "delete">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}", "delete"> }>({
    mutationFn: (vars) => request("/projects/{project}/reports/{number}", "delete", { params: (vars as any).params }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useDeleteReportMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useGenerateReportMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}/reports/{number}/generate", "post">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}/generate", "post">; body: RequestBody<"/projects/{project}/reports/{number}/generate", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}/reports/{number}/generate", "post">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}/generate", "post">; body: RequestBody<"/projects/{project}/reports/{number}/generate", "post"> }>({
    mutationFn: (vars) => request("/projects/{project}/reports/{number}/generate", "post", { params: (vars as any).params, body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useGenerateReportMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useRegenerateReportMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}/reports/{number}/regenerate", "post">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}/regenerate", "post">; body: RequestBody<"/projects/{project}/reports/{number}/regenerate", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}/reports/{number}/regenerate", "post">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}/regenerate", "post">; body: RequestBody<"/projects/{project}/reports/{number}/regenerate", "post"> }>({
    mutationFn: (vars) => request("/projects/{project}/reports/{number}/regenerate", "post", { params: (vars as any).params, body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useRegenerateReportMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useFinalizeReportMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}/reports/{number}/finalize", "post">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}/finalize", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}/reports/{number}/finalize", "post">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}/finalize", "post"> }>({
    mutationFn: (vars) => request("/projects/{project}/reports/{number}/finalize", "post", { params: (vars as any).params }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useFinalizeReportMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useUnfinalizeReportMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}/reports/{number}/unfinalize", "post">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}/unfinalize", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}/reports/{number}/unfinalize", "post">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}/unfinalize", "post"> }>({
    mutationFn: (vars) => request("/projects/{project}/reports/{number}/unfinalize", "post", { params: (vars as any).params }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useUnfinalizeReportMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useReportPdfMutation(
  options?: UseMutationOptions<ResponseBody<"/projects/{project}/reports/{number}/pdf", "post">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}/pdf", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/projects/{project}/reports/{number}/pdf", "post">, ApiError, { params: PathParams<"/projects/{project}/reports/{number}/pdf", "post"> }>({
    mutationFn: (vars) => request("/projects/{project}/reports/{number}/pdf", "post", { params: (vars as any).params }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useReportPdfMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useReportDebugQuery(
  input: { params: PathParams<"/projects/{project}/reports/{number}/debug", "get">; query?: QueryParams<"/projects/{project}/reports/{number}/debug", "get"> },
  options?: Omit<UseQueryOptions<ResponseBody<"/projects/{project}/reports/{number}/debug", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/projects/{project}/reports/{number}/debug", "get">, ApiError>({
    queryKey: ["reportDebug", (input as any).params, (input as any).query] as const,
    queryFn: ({ signal }) => request("/projects/{project}/reports/{number}/debug", "get", { params: (input as any).params, query: (input as any).query, signal }),
    ...options,
  });
}

// ─── p ───────────────────────────────────────────
export function useResolveProjectSlugQuery(
  input: { params: PathParams<"/p/{project}", "get">; query?: QueryParams<"/p/{project}", "get"> },
  options?: Omit<UseQueryOptions<ResponseBody<"/p/{project}", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/p/{project}", "get">, ApiError>({
    queryKey: ["resolveProjectSlug", (input as any).params, (input as any).query] as const,
    queryFn: ({ signal }) => request("/p/{project}", "get", { params: (input as any).params, query: (input as any).query, signal }),
    ...options,
  });
}

// ─── r ───────────────────────────────────────────
export function useResolveReportSlugQuery(
  input: { params: PathParams<"/r/{report}", "get">; query?: QueryParams<"/r/{report}", "get"> },
  options?: Omit<UseQueryOptions<ResponseBody<"/r/{report}", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/r/{report}", "get">, ApiError>({
    queryKey: ["resolveReportSlug", (input as any).params, (input as any).query] as const,
    queryFn: ({ signal }) => request("/r/{report}", "get", { params: (input as any).params, query: (input as any).query, signal }),
    ...options,
  });
}

// ─── reports ───────────────────────────────────────────
export function useReportNotesQuery(
  input: { params: PathParams<"/reports/{report}/notes", "get">; query?: QueryParams<"/reports/{report}/notes", "get"> },
  options?: Omit<UseQueryOptions<ResponseBody<"/reports/{report}/notes", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/reports/{report}/notes", "get">, ApiError>({
    queryKey: ["reportNotes", (input as any).params, (input as any).query] as const,
    queryFn: ({ signal }) => request("/reports/{report}/notes", "get", { params: (input as any).params, query: (input as any).query, signal }),
    ...options,
  });
}

export function useCreateNoteMutation(
  options?: UseMutationOptions<ResponseBody<"/reports/{report}/notes", "post">, ApiError, { params: PathParams<"/reports/{report}/notes", "post">; body: RequestBody<"/reports/{report}/notes", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/reports/{report}/notes", "post">, ApiError, { params: PathParams<"/reports/{report}/notes", "post">; body: RequestBody<"/reports/{report}/notes", "post"> }>({
    mutationFn: (vars) => request("/reports/{report}/notes", "post", { params: (vars as any).params, body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useCreateNoteMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useCreateVoiceNoteMutation(
  options?: UseMutationOptions<ResponseBody<"/reports/{report}/notes/voice", "post">, ApiError, { params: PathParams<"/reports/{report}/notes/voice", "post">; body: RequestBody<"/reports/{report}/notes/voice", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/reports/{report}/notes/voice", "post">, ApiError, { params: PathParams<"/reports/{report}/notes/voice", "post">; body: RequestBody<"/reports/{report}/notes/voice", "post"> }>({
    mutationFn: (vars) => request("/reports/{report}/notes/voice", "post", { params: (vars as any).params, body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useCreateVoiceNoteMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

// ─── notes ───────────────────────────────────────────
export function useUpdateNoteMutation(
  options?: UseMutationOptions<ResponseBody<"/notes/{note}", "patch">, ApiError, { params: PathParams<"/notes/{note}", "patch">; body: RequestBody<"/notes/{note}", "patch"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/notes/{note}", "patch">, ApiError, { params: PathParams<"/notes/{note}", "patch">; body: RequestBody<"/notes/{note}", "patch"> }>({
    mutationFn: (vars) => request("/notes/{note}", "patch", { params: (vars as any).params, body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useUpdateNoteMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useDeleteNoteMutation(
  options?: UseMutationOptions<ResponseBody<"/notes/{note}", "delete">, ApiError, { params: PathParams<"/notes/{note}", "delete"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/notes/{note}", "delete">, ApiError, { params: PathParams<"/notes/{note}", "delete"> }>({
    mutationFn: (vars) => request("/notes/{note}", "delete", { params: (vars as any).params }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useDeleteNoteMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

// ─── files ───────────────────────────────────────────
export function usePresignFileMutation(
  options?: UseMutationOptions<ResponseBody<"/files/presign", "post">, ApiError, { body: RequestBody<"/files/presign", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/files/presign", "post">, ApiError, { body: RequestBody<"/files/presign", "post"> }>({
    mutationFn: (vars) => request("/files/presign", "post", { body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["usePresignFileMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useCreateFileMutation(
  options?: UseMutationOptions<ResponseBody<"/files", "post">, ApiError, { body: RequestBody<"/files", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/files", "post">, ApiError, { body: RequestBody<"/files", "post"> }>({
    mutationFn: (vars) => request("/files", "post", { body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useCreateFileMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useFileUrlQuery(
  input: { params: PathParams<"/files/{id}/url", "get">; query?: QueryParams<"/files/{id}/url", "get"> },
  options?: Omit<UseQueryOptions<ResponseBody<"/files/{id}/url", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/files/{id}/url", "get">, ApiError>({
    queryKey: ["fileUrl", (input as any).params, (input as any).query] as const,
    queryFn: ({ signal }) => request("/files/{id}/url", "get", { params: (input as any).params, query: (input as any).query, signal }),
    ...options,
  });
}

// ─── voice ───────────────────────────────────────────
export function useTranscribeVoiceMutation(
  options?: UseMutationOptions<ResponseBody<"/voice/transcribe", "post">, ApiError, { body: RequestBody<"/voice/transcribe", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/voice/transcribe", "post">, ApiError, { body: RequestBody<"/voice/transcribe", "post"> }>({
    mutationFn: (vars) => request("/voice/transcribe", "post", { body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useTranscribeVoiceMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

export function useSummarizeVoiceMutation(
  options?: UseMutationOptions<ResponseBody<"/voice/summarize", "post">, ApiError, { body: RequestBody<"/voice/summarize", "post"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/voice/summarize", "post">, ApiError, { body: RequestBody<"/voice/summarize", "post"> }>({
    mutationFn: (vars) => request("/voice/summarize", "post", { body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useSummarizeVoiceMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

// ─── settings ───────────────────────────────────────────
export function useAiSettingsQuery(
  input?: { query?: QueryParams<"/settings/ai", "get"> } | void,
  options?: Omit<UseQueryOptions<ResponseBody<"/settings/ai", "get">, ApiError>, 'queryKey' | 'queryFn'>,
) {
  return useQuery<ResponseBody<"/settings/ai", "get">, ApiError>({
    queryKey: ["aiSettings", (input as any)?.query] as const,
    queryFn: ({ signal }) => request("/settings/ai", "get", { query: (input as any)?.query, signal }),
    ...options,
  });
}

export function useUpdateAiSettingsMutation(
  options?: UseMutationOptions<ResponseBody<"/settings/ai", "patch">, ApiError, { body: RequestBody<"/settings/ai", "patch"> }>,
) {
  const qc = useQueryClient();
  return useMutation<ResponseBody<"/settings/ai", "patch">, ApiError, { body: RequestBody<"/settings/ai", "patch"> }>({
    mutationFn: (vars) => request("/settings/ai", "patch", { body: (vars as any).body }),
    ...options,
    onSuccess: (...args) => {
      const rule = INVALIDATIONS["useUpdateAiSettingsMutation"];
      if (rule && rule !== INVALIDATIONS_NONE) {
        for (const head of rule) {
          qc.invalidateQueries({ queryKey: [head] });
        }
      }
      return options?.onSuccess?.(...args);
    },
  });
}

