/**
 * Integration tests for /projects + /projects/:id/members.
 * Boots Testcontainers Postgres and exercises the full request →
 * scope wrapper → SECURITY DEFINER helper path end-to-end.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { createApp } from '../app.js';
import { startPg, seedAuthUsers, type PgFixture } from './setup-pg.js';
import { resetPool, getPool } from '../db/client.js';
import { signTestToken } from '../middleware/auth.js';
import { makeUserId, makeSessionId } from './factories/index.js';

let fx: PgFixture;
let alice: string;
let bob: string;
let carol: string;
let aliceSid: string;
let bobSid: string;
let carolSid: string;

beforeAll(async () => {
  fx = await startPg();
  process.env.DATABASE_URL = fx.url;
  await resetPool();
  getPool(fx.url);

  alice = makeUserId();
  bob = makeUserId();
  carol = makeUserId();
  aliceSid = makeSessionId();
  bobSid = makeSessionId();
  carolSid = makeSessionId();

  await seedAuthUsers(fx.url, [
    { id: alice, displayName: 'Alice' },
    { id: bob, displayName: 'Bob' },
    { id: carol, displayName: 'Carol' },
  ]);
}, 120_000);

afterAll(async () => {
  await fx?.stop();
}, 60_000);

async function authed(token: string) {
  return { authorization: `Bearer ${token}`, 'content-type': 'application/json' };
}

describe('POST /projects', () => {
  it('creates a project owned by the caller and bootstraps owner membership', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request('/projects', {
      method: 'POST',
      headers: await authed(token),
      body: JSON.stringify({ name: 'Foundation Pour', clientName: 'ACME', address: '1 Pier' }),
    });
    expect(res.status).toBe(201);
    const body = (await res.json()) as {
      id: string;
      slug: string;
      ownerId: string;
      myRole: string;
      name: string;
    };
    expect(body.name).toBe('Foundation Pour');
    expect(body.ownerId).toBe(alice);
    expect(body.myRole).toBe('owner');
    // P3.0 Commit 2: response carries a `prj_` Crockford-base32 slug
    // generated by services/projects.ts.createProject (retry-on-collision).
    expect(body.id).toMatch(/^prj_[0-9a-hjkmnp-tv-z]{8}$/);
  });

  it('rejects 401 without auth', async () => {
    const app = createApp();
    const res = await app.request('/projects', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ name: 'x' }),
    });
    expect(res.status).toBe(401);
  });

  it('rejects 400 for empty name', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request('/projects', {
      method: 'POST',
      headers: await authed(token),
      body: JSON.stringify({ name: '' }),
    });
    expect(res.status).toBe(400);
  });
});

describe('GET /projects + GET /projects/:id', () => {
  let projectSlug: string;

  beforeAll(async () => {
    const app = createApp();
    const token = await signTestToken(bob, bobSid);
    const res = await app.request('/projects', {
      method: 'POST',
      headers: await authed(token),
      body: JSON.stringify({ name: 'Bob site' }),
    });
    const body = (await res.json()) as { id: string };
    projectSlug = body.id;
  });

  it('lists projects for the caller (paginated)', async () => {
    const app = createApp();
    const token = await signTestToken(bob, bobSid);
    const res = await app.request('/projects?limit=5', { headers: { authorization: `Bearer ${token}` } });
    expect(res.status).toBe(200);
    const body = (await res.json()) as { items: Array<{ id: string }>; nextCursor: string | null };
    expect(body.items.length).toBeGreaterThan(0);
    expect(body.items.find((p) => p.id === projectSlug)).toBeTruthy();
  });

  it('cursor pagination round-trips', async () => {
    const app = createApp();
    const token = await signTestToken(bob, bobSid);
    // Seed 4 more so we can paginate across.
    for (let i = 0; i < 4; i++) {
      await app.request('/projects', {
        method: 'POST',
        headers: await authed(token),
        body: JSON.stringify({ name: `Bob extra ${i}` }),
      });
    }
    const first = await app.request('/projects?limit=2', { headers: { authorization: `Bearer ${token}` } });
    const firstBody = (await first.json()) as { items: Array<{ id: string }>; nextCursor: string | null };
    expect(firstBody.items.length).toBe(2);
    expect(firstBody.nextCursor).not.toBeNull();
    const second = await app.request(`/projects?limit=2&cursor=${encodeURIComponent(firstBody.nextCursor!)}`, {
      headers: { authorization: `Bearer ${token}` },
    });
    const secondBody = (await second.json()) as { items: Array<{ id: string }>; nextCursor: string | null };
    expect(secondBody.items.length).toBe(2);
    expect(new Set(firstBody.items.map((i) => i.id)).has(secondBody.items[0]!.id)).toBe(false);
  });

  it('GET /projects/:id returns stats', async () => {
    const app = createApp();
    const token = await signTestToken(bob, bobSid);
    const res = await app.request(`/projects/${projectSlug}`, { headers: { authorization: `Bearer ${token}` } });
    expect(res.status).toBe(200);
    const body = (await res.json()) as { stats?: { totalReports: number } };
    expect(body.stats?.totalReports).toBe(0);
  });

  it('GET /projects/:id 404 when not a member', async () => {
    const app = createApp();
    const token = await signTestToken(carol, carolSid);
    const res = await app.request(`/projects/${projectSlug}`, { headers: { authorization: `Bearer ${token}` } });
    expect(res.status).toBe(404);
  });

  it('GET /projects/:id 401 without auth', async () => {
    const app = createApp();
    const res = await app.request(`/projects/${projectSlug}`);
    expect(res.status).toBe(401);
  });
});

describe('PATCH + DELETE /projects/:id', () => {
  let projectSlug: string;
  beforeAll(async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request('/projects', {
      method: 'POST',
      headers: await authed(token),
      body: JSON.stringify({ name: 'Patchable' }),
    });
    projectSlug = ((await res.json()) as { id: string }).id;
  });

  it('PATCH updates fields the caller can see', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request(`/projects/${projectSlug}`, {
      method: 'PATCH',
      headers: await authed(token),
      body: JSON.stringify({ name: 'Patched' }),
    });
    expect(res.status).toBe(200);
    expect(((await res.json()) as { name: string }).name).toBe('Patched');
  });

  it('DELETE returns 204 for owner', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request(`/projects/${projectSlug}`, {
      method: 'DELETE',
      headers: { authorization: `Bearer ${token}` },
    });
    expect(res.status).toBe(204);
  });

  it('DELETE 404 when not owner', async () => {
    // alice creates, bob is invited as editor → cannot delete.
    const app = createApp();
    const aliceTok = await signTestToken(alice, aliceSid);
    const bobTok = await signTestToken(bob, bobSid);
    const created = await app.request('/projects', {
      method: 'POST',
      headers: await authed(aliceTok),
      body: JSON.stringify({ name: 'NotYours' }),
    });
    const slug = ((await created.json()) as { id: string }).id;
    await app.request(`/projects/${slug}/members`, {
      method: 'POST',
      headers: await authed(aliceTok),
      body: JSON.stringify({ email: `${bob}@test.local`, role: 'editor' }),
    });
    const res = await app.request(`/projects/${slug}`, {
      method: 'DELETE',
      headers: { authorization: `Bearer ${bobTok}` },
    });
    expect(res.status).toBe(404);
  });
});

describe('Members', () => {
  let projectSlug: string;
  beforeAll(async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request('/projects', {
      method: 'POST',
      headers: await authed(token),
      body: JSON.stringify({ name: 'MemberTest' }),
    });
    projectSlug = ((await res.json()) as { id: string }).id;
  });

  it('owner invites a member by phone', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request(`/projects/${projectSlug}/members`, {
      method: 'POST',
      headers: await authed(token),
      body: JSON.stringify({ email: `${bob}@test.local`, role: 'editor' }),
    });
    expect(res.status).toBe(201);
    const body = (await res.json()) as { userId: string; email: string; role: string };
    expect(body.userId).toBe(bob);
    expect(body.role).toBe('editor');
  });

  it('list members visible to a member', async () => {
    const app = createApp();
    const token = await signTestToken(bob, bobSid);
    const res = await app.request(`/projects/${projectSlug}/members`, { headers: { authorization: `Bearer ${token}` } });
    expect(res.status).toBe(200);
    const body = (await res.json()) as { items: Array<{ userId: string }> };
    expect(body.items.length).toBe(2);
  });

  it('list members 404 for non-member', async () => {
    const app = createApp();
    const token = await signTestToken(carol, carolSid);
    const res = await app.request(`/projects/${projectSlug}/members`, { headers: { authorization: `Bearer ${token}` } });
    expect(res.status).toBe(404);
  });

  it('non-owner invite returns 403', async () => {
    const app = createApp();
    const token = await signTestToken(bob, bobSid);
    const res = await app.request(`/projects/${projectSlug}/members`, {
      method: 'POST',
      headers: await authed(token),
      body: JSON.stringify({ email: `${carol}@test.local`, role: 'editor' }),
    });
    expect(res.status).toBe(403);
  });

  it('invite unknown phone returns 404', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request(`/projects/${projectSlug}/members`, {
      method: 'POST',
      headers: await authed(token),
      body: JSON.stringify({ email: 'unknown@test.local', role: 'editor' }),
    });
    expect(res.status).toBe(404);
  });

  it('owner removes a member', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request(`/projects/${projectSlug}/members/${bob}`, {
      method: 'DELETE',
      headers: { authorization: `Bearer ${token}` },
    });
    expect(res.status).toBe(204);
  });

  it('cannot remove the last owner', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request(`/projects/${projectSlug}/members/${alice}`, {
      method: 'DELETE',
      headers: { authorization: `Bearer ${token}` },
    });
    expect(res.status).toBe(409);
  });

  it('re-inviting an existing member returns 409 instead of demoting their role', async () => {
    // Fresh project so the test is independent of suite ordering.
    const app = createApp();
    const aliceTok = await signTestToken(alice, aliceSid);
    const create = await app.request('/projects', {
      method: 'POST',
      headers: await authed(aliceTok),
      body: JSON.stringify({ name: 'DemotionGuard' }),
    });
    const slug = ((await create.json()) as { id: string }).id;
    // First invite succeeds, makes bob an editor.
    const first = await app.request(`/projects/${slug}/members`, {
      method: 'POST',
      headers: await authed(aliceTok),
      body: JSON.stringify({ email: `${bob}@test.local`, role: 'editor' }),
    });
    expect(first.status).toBe(201);
    // Re-invite must NOT silently overwrite role.
    const second = await app.request(`/projects/${slug}/members`, {
      method: 'POST',
      headers: await authed(aliceTok),
      body: JSON.stringify({ email: `${bob}@test.local`, role: 'viewer' }),
    });
    expect(second.status).toBe(409);
    // Confirm bob is still editor, not viewer.
    const list = await app.request(`/projects/${slug}/members`, {
      headers: { authorization: `Bearer ${aliceTok}` },
    });
    const body = (await list.json()) as { items: Array<{ userId: string; role: string }> };
    const bobRow = body.items.find((m) => m.userId === bob);
    expect(bobRow?.role).toBe('editor');
  });

  it('re-inviting the owner cannot demote them (last owner protection)', async () => {
    const app = createApp();
    const aliceTok = await signTestToken(alice, aliceSid);
    const create = await app.request('/projects', {
      method: 'POST',
      headers: await authed(aliceTok),
      body: JSON.stringify({ name: 'OwnerDemoteGuard' }),
    });
    const slug = ((await create.json()) as { id: string }).id;
    // Alice tries to re-invite herself as editor — must fail.
    const res = await app.request(`/projects/${slug}/members`, {
      method: 'POST',
      headers: await authed(aliceTok),
      body: JSON.stringify({ email: `${alice}@test.local`, role: 'editor' }),
    });
    expect(res.status).toBe(409);
    // Alice should still be owner.
    const list = await app.request(`/projects/${slug}/members`, {
      headers: { authorization: `Bearer ${aliceTok}` },
    });
    const body = (await list.json()) as { items: Array<{ userId: string; role: string }> };
    expect(body.items.find((m) => m.userId === alice)?.role).toBe('owner');
  });
});

describe('PATCH /projects/:id/members/:user', () => {
  let projectSlug: string;

  beforeAll(async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request('/projects', {
      method: 'POST',
      headers: await authed(token),
      body: JSON.stringify({ name: 'PatchMemberRole' }),
    });
    projectSlug = ((await res.json()) as { id: string }).id;
    // Add bob as editor, carol as editor so we have subjects to patch.
    await app.request(`/projects/${projectSlug}/members`, {
      method: 'POST',
      headers: await authed(token),
      body: JSON.stringify({ email: `${bob}@test.local`, role: 'editor' }),
    });
    await app.request(`/projects/${projectSlug}/members`, {
      method: 'POST',
      headers: await authed(token),
      body: JSON.stringify({ email: `${carol}@test.local`, role: 'editor' }),
    });
  });

  // P1: owner promotes editor to owner
  it('P1 owner promotes editor B to owner', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request(`/projects/${projectSlug}/members/${bob}`, {
      method: 'PATCH',
      headers: await authed(token),
      body: JSON.stringify({ role: 'owner' }),
    });
    expect(res.status).toBe(200);
    expect(((await res.json()) as { role: string }).role).toBe('owner');
  });

  // P2: owner demotes co-owner (two owners exist)
  it('P2 owner demotes co-owner B when two owners exist', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    // At this point alice + bob are both owners.
    const res = await app.request(`/projects/${projectSlug}/members/${bob}`, {
      method: 'PATCH',
      headers: await authed(token),
      body: JSON.stringify({ role: 'editor' }),
    });
    expect(res.status).toBe(200);
    expect(((await res.json()) as { role: string }).role).toBe('editor');
  });

  // P3: sole owner tries to demote themselves
  it('P3 sole owner cannot demote themselves', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request(`/projects/${projectSlug}/members/${alice}`, {
      method: 'PATCH',
      headers: await authed(token),
      body: JSON.stringify({ role: 'editor' }),
    });
    expect(res.status).toBe(409);
  });

  // P4: owner tries to demote another member who is sole owner
  it('P4 owner cannot demote sole owner even if target is different user', async () => {
    // Make bob the owner again then demote alice, leaving bob as sole owner.
    const app = createApp();
    const aliceTok = await signTestToken(alice, aliceSid);
    // Promote bob to owner.
    await app.request(`/projects/${projectSlug}/members/${bob}`, {
      method: 'PATCH',
      headers: await authed(aliceTok),
      body: JSON.stringify({ role: 'owner' }),
    });
    // Demote alice herself (now alice and bob are both owners).
    await app.request(`/projects/${projectSlug}/members/${alice}`, {
      method: 'PATCH',
      headers: await authed(aliceTok),
      body: JSON.stringify({ role: 'editor' }),
    });
    // Now bob is sole owner; log in as bob and try to demote himself.
    const bobTok = await signTestToken(bob, bobSid);
    const res = await app.request(`/projects/${projectSlug}/members/${bob}`, {
      method: 'PATCH',
      headers: await authed(bobTok),
      body: JSON.stringify({ role: 'editor' }),
    });
    expect(res.status).toBe(409);
    // Restore: re-promote alice so remaining tests have an owner.
    await app.request(`/projects/${projectSlug}/members/${alice}`, {
      method: 'PATCH',
      headers: await authed(bobTok),
      body: JSON.stringify({ role: 'owner' }),
    });
  });

  // P5: idempotent same-role patch
  it('P5 same-role PATCH returns 200 unchanged', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    // Bob is editor after P2.
    const res = await app.request(`/projects/${projectSlug}/members/${bob}`, {
      method: 'PATCH',
      headers: await authed(token),
      body: JSON.stringify({ role: 'editor' }),
    });
    expect(res.status).toBe(200);
    expect(((await res.json()) as { role: string }).role).toBe('editor');
  });

  // P6: non-owner cannot patch
  it('P6 editor cannot patch any member role', async () => {
    const app = createApp();
    const token = await signTestToken(bob, bobSid); // bob is editor
    const res = await app.request(`/projects/${projectSlug}/members/${carol}`, {
      method: 'PATCH',
      headers: await authed(token),
      body: JSON.stringify({ role: 'owner' }),
    });
    expect(res.status).toBe(403);
  });

  // P7: patching a non-member returns 404
  it('P7 patching a non-member returns 404', async () => {
    const app = createApp();
    const token = await signTestToken(alice, aliceSid);
    const res = await app.request(`/projects/${projectSlug}/members/usr_aaaaaaaaaa`, {
      method: 'PATCH',
      headers: await authed(token),
      body: JSON.stringify({ role: 'editor' }),
    });
    expect(res.status).toBe(404);
  });

  // P8: cross-project: owner A cannot patch members of a project they don't belong to
  it('P8 cross-project patch is 404 (project invisible)', async () => {
    const app = createApp();
    // Bob creates his own project.
    const bobTok = await signTestToken(bob, bobSid);
    const created = await app.request('/projects', {
      method: 'POST',
      headers: await authed(bobTok),
      body: JSON.stringify({ name: 'BobOnly' }),
    });
    const bobSlug = ((await created.json()) as { id: string }).id;
    // Alice tries to patch bob's project members — she's not a member.
    const aliceTok = await signTestToken(alice, aliceSid);
    const res = await app.request(`/projects/${bobSlug}/members/${bob}`, {
      method: 'PATCH',
      headers: await authed(aliceTok),
      body: JSON.stringify({ role: 'editor' }),
    });
    expect(res.status).toBe(404);
  });

  // 401 without auth
  it('returns 401 without auth', async () => {
    const app = createApp();
    const res = await app.request(`/projects/${projectSlug}/members/${bob}`, {
      method: 'PATCH',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ role: 'editor' }),
    });
    expect(res.status).toBe(401);
  });
});
