/**
 * EditTabPane — inline section editor for the generated report.
 *
 * Ported from
 * `../haru3-reports/apps/mobile/components/reports/generate/EditTabPane.tsx`
 * on branch `dev`. Mounts `ReportEditForm` once a report exists (either
 * generated by the AI or lazily seeded via `createEmptyReport` when
 * the user opens this tab without one), and shows an empty state
 * otherwise. The header row exposes a small autosave status string
 * driven by `draft.isAutoSaving` / `draft.lastSavedAt` — the real
 * autosave hook lands later; for now the provider just forwards
 * whatever the route wires in.
 */
import { FileText } from 'lucide-react-native';
import { ScrollView, Text, View } from 'react-native';

import { EmptyState } from '@/components/primitives/EmptyState';
import { ReportEditForm } from '@/components/reports/ReportEditForm';
import { useGenerateReport } from '@/components/reports/generate/GenerateReportProvider';
import { colors } from '@/lib/design-tokens/colors';

interface EditTabPaneProps {
  width: number;
}

export function EditTabPane({ width }: EditTabPaneProps) {
  const { generation, draft } = useGenerateReport();

  return (
    <View style={{ width }} className="flex-1" testID="edit-tab-pane">
      {generation.report ? (
        <View className="flex-1" testID="edit-tab-form">
          <View className="flex-row items-center justify-between px-5 pt-2 pb-1">
            <Text className="text-sm font-medium text-muted-foreground">
              Edit report
            </Text>
            <Text
              className="text-xs text-muted-foreground"
              testID="edit-autosave-status"
            >
              {draft.isAutoSaving ? 'Saving…' : draft.lastSavedAt ? 'Saved' : ''}
            </Text>
          </View>
          <ReportEditForm
            report={generation.report}
            onChange={generation.setReport}
          />
        </View>
      ) : (
        <ScrollView
          className="flex-1 px-5"
          contentContainerStyle={{ paddingBottom: 100 }}
          testID="edit-tab-empty"
        >
          <EmptyState
            icon={<FileText size={28} color={colors.muted.foreground} />}
            title="Generate a report first to edit"
            description="Once your report is generated from the notes, you can edit any field here."
          />
        </ScrollView>
      )}
    </View>
  );
}

