/// <reference types="vitest/config" />
import { defineConfig } from 'vitest/config';
import path from 'node:path';

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, '.'),
    },
  },
  // React Native / Expo modules reference `__DEV__` as a global. Vitest
  // doesn't provide it, so define it as a compile-time constant for any
  // transitively-imported native modules.
  define: {
    __DEV__: 'false',
  },
  // Repo tsconfig uses `jsx="react-native"` (RN babel handles it at
  // runtime). Vitest uses esbuild — override to the automatic runtime
  // so test files don't need `import React`.
  esbuild: {
    jsx: 'automatic',
  },
  test: {
    globals: false,
    environment: 'node',
    setupFiles: ['./vitest.setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text-summary', 'json-summary', 'html'],
      reportsDirectory: './coverage',
      // Cover the source tree the tests are aimed at; exclude
      // generated, vendor, test, snapshot, fixture, and runtime-only
      // (route layouts / Expo entrypoints) surfaces so coverage
      // reflects logic we can actually unit-test in node + jsdom.
      include: [
        'lib/**/*.{ts,tsx}',
        'features/**/*.{ts,tsx}',
        'components/**/*.{ts,tsx}',
        'screens/**/*.{ts,tsx}',
      ],
      exclude: [
        '**/*.test.{ts,tsx}',
        '**/__tests__/**',
        '**/__snapshots__/**',
        '**/__fixtures__/**',
        '**/__mocks__/**',
        '**/*.d.ts',
        // Auto-generated by scripts/gen-hooks.ts (spec-drift gate
        // already enforces it's in sync with the OpenAPI contract).
        'lib/api/hooks.ts',
        'lib/api/hooks.gen.ts',
        'lib/dev-fixtures/**',
        // Thin shims over native modules — exercised end-to-end by
        // Maestro, not unit tests. No logic worth covering in node.
        'lib/native/**',
        'features/voice/expoAudioRecorder.ts',
        // better-auth client wiring (SecureStore-backed cookie storage,
        // expoClient plugin config). Pure runtime glue — exercised by
        // Maestro E2E auth flows, not unit tests. Same rationale as
        // lib/native/**.
        'lib/auth/client.ts',
        'lib/auth/index.ts',
      ],
      // Thresholds reflect what unit tests can realistically cover:
      // we exclude auto-generated hooks and native module shims (no
      // logic worth testing in node), so these numbers gate the
      // hand-written app surface.
      //
      // P3 exit-gate target: lines ≥ 80%
      // (docs/v4/plan-p3-feature-build.md). Current baseline:
      //   lines 81.84% · statements 81.84% · branches 79.41% · functions 73%
      // Ratchet up only — never lower these numbers without a
      // documented reason.
      //
      // 2026-06: functions threshold lowered 72→71 as report editing moved
      // from the inline Generate surface to the per-card modal flow
      // (see docs/superpowers/specs/2026-06-03-report-edit-modal-redesign-design.md).
      // The remaining unreachable Generate Edit code was removed in 2026-08;
      // the full suite remains above every threshold.
      thresholds: {
        lines: 80,
        statements: 80,
        functions: 71,
        branches: 79,
      },
    },
    include: [
      'lib/**/*.test.ts',
      'lib/**/*.test.tsx',
      'screens/**/*.test.ts',
      'screens/**/*.test.tsx',
      'components/**/*.test.ts',
      'components/**/*.test.tsx',
      'features/**/*.test.ts',
      'features/**/*.test.tsx',
      'app/**/*.test.ts',
      'app/**/*.test.tsx',
      '__tests__/**/*.test.ts',
      '__tests__/**/*.test.tsx',
    ],
    exclude: ['node_modules', '.expo', 'dist'],
  },
});
